services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/app/
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - SETUPTOOLS_USE_DISTUTILS=stdlib

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow_data:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0